baseURL = 'https://juicebar-demo.add1.dev/'
languageCode = 'en'
# languageCode = 'zh-CN'
theme = "JuiceBar"
title = "Riveer -  learning from zero"

[params]
author = "hanafi"
description = "My site description"
authorImage = "/images/pp.jpg"
paginate = 5

Title = "Hanafi"
content = "Hello I'm hanafi, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/pp.jpg"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "Github"
url = "https://github.com/Hanaf1"
[[params.social]]
name = "instagram"
url = "https://www.instagram.com/hanaf1_v1"

[taxonomies]
category = "categories"

# To add a new navigation link
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

[params.giscus]
repo = "hotjuicew/blog"
repoID = "R_kgDOHHQOuw"
category = "Announcements"
categoryID = "DIC_kwDOHHQOu84CWCQ3"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]



